### ISSUE TITLE
[BUG] Overflow avec scrollbar pour les agents

### ISSUE THREAD

**Issue by johangirod** [etalab/annuaire-entreprises-site#1025]
![image](https://github.com/etalab/annuaire-entreprises-site/assets/1775934/3be328cf-2445-47c4-9210-336165324d79)

Commence à largeur 1000px environ

**Comment by XavierJp** [comment]
Je veux bien le prendre
Est ce que tu as un siren pour tester ?

**Comment by johangirod** [comment]
@XavierJp Classique Danone https://annuaire-entreprises.data.gouv.fr/entreprise/danone-552032534
