### ISSUE TITLE
Landing pages : RGE, ESS, Spectacle Vivant

### ISSUE THREAD

**Issue by XavierJp** [etalab/annuaire-entreprises-site#254]

**Comment by Jonathan2051** [comment]
PAGE ESS : https://test.annuaire-entreprises.data.gouv.fr/rechercher/ess

**NOUVEL INTITULÉ DE LIEN**

Rechercher une entreprise de l’ESS

**NOUVEAU TITLE**

Rechercher une entreprise ou une association de l’ESS | Annuaire Entreprises

**NOUVELLE META DESCRIPTION**

L’administration permet aux particuliers et agents publics de vérifier les informations juridiques officielles d’une entreprise de l’Economie Sociale et Solidaire (ESS) : SIREN, SIRET, TVA Intracommunautaire, code APE/NAF, capital social, justificatif d’immatriculation, dirigeants, convention collective…

**NOUVEAU < H1 >**

Rechercher une entreprise  de l’ESS

NOUVEAU < H2 >

Vérifiez toutes les informations juridiques publiques d’une entreprise de l’Economie Social et solidaire

**ANCIEN INTITULÉ DE LIEN**

ESS - Economie Sociale et Solidaire

**ANCIEN TITLE**

Moteur de recherche des Entreprises de l’ESS

**ANCIENNE META DESCRIPTION**

Retrouvez une entreprise appartenant au champ de l’Economie Sociale et Solidaire)

**ANCIEN < H1 >**

Moteur de recherche des Entreprises ESS

ANCIEN < H2 >

Retrouvez une entreprise appartenant au champ de l'Economie Sociale et Solidaire)
