### ISSUE TITLE
La liste des entreprise d'un dirigeant n'inclut pas son entreprise individuelle

### ISSUE THREAD

**Issue by mquandalle** [etalab/annuaire-entreprises-site#271]
Bonjour et bonne année ! Et bravo pour toutes les améliorations sur l'annuaire ces derniers mois, c'est vraiment un outil génial !

J'ai remarqué que la fonctionnalité « voir ses entreprises » sur un dirigeant d'entreprise n'inclut pas les entreprises individuelles, par exemple :

Via https://annuaire-entreprises.data.gouv.fr/dirigeants/921389169 je n'accède ni à https://annuaire-entreprises.data.gouv.fr/entreprise/850556812 ni à https://annuaire-entreprises.data.gouv.fr/entreprise/834825614

Edit: j'imagine que c'est lié à une limite dans les données... d'ailleurs je vois le même problème sur https://www.societe.com/societe/mon-entreprise-portage-921389169.html

Peut-être qu'il faudrait ajouter une phrase sur la page des entreprises d'un dirigeant pour préciser que la liste n'est pas forcément exhaustive ?

**Comment by XavierJp** [comment]
Merci @mquandalle désolé pour le long délai de réponse. En effet, limite dans les données. Il devait manquer les sociétés artisanales également.

Avec la migration vers le RNE il devient encore plus difficile d'identifier à coup sur les entreprises d'un(e) dirigeant(e). J'ai donc reformulé les explications de la page `/personne` et j'ai créé un warning en haut de page pour alerter sur les possible risque d'homonymie.

Le RNE devrait cependant amener les EI à intégrer progressivement la recherche par dirigeant, les EI étant dans le scope du RNE (et pas du RNCS).
