### ISSUE TITLE
Optimiser les TITLE + DESCRIPTION

### ISSUE THREAD

**Issue by XavierJp** [etalab/annuaire-entreprises-site#283]
Actuellement :

```
title : Société - SIREN 880878145, 88087814500015, 62.02A - Conseil en systèmes et logiciels informatiques | Annuaire Entreprises

description :  Toutes les informations officielles sur GANYMEDE : Siren, Siret, NIC, APE/NAF, N° TVA, capital social, justificatif d’immatriculation, diri…
```

Objectif :

``` 
title : 
Société {Dénomination} à {ville} siren {SIREN} sur {nom du site}
Association {Dénomination} à {ville} siren {SIREN} sur {nom du site}
Administration {Dénomination} à {ville} siren {SIREN} sur {nom du site}

description : L’administration permet aux particuliers et agents publics de vérifier les informations juridiques officielles de {denomination} à {ville} ({code postal}) : SIREN, SIRET, TVA Intracommunautaire, Code APE/NAF, dirigeant, adresse, justificatif  d'immatriculation...
```

Limites : 
- title -> pas de limite
- description -> pas de limite

**Comment by XavierJp** [comment]
@Jonathan2051

**Comment by Jonathan2051** [comment]
Résultat attendu :

TITLE : Société GANYMEDE à PARIS 8 - informations juridiques - SIREN 880878145 | Annuaire Entreprises

_LC = lettres capitales_

Société {Dénomination en LC} à {ville en LC} - informations juridiques - SIREN {N° de SIREN} | Annuaire Entreprises
Association {Dénomination en LC} à {ville LC} - informations juridiques - SIREN {N° de SIREN} | Annuaire Entreprises
Administration {Dénomination LC} à {ville LC} - informations juridiques - SIREN {N° de SIREN} | Annuaire Entreprises
