### ISSUE TITLE
[BUG] Natures juridiques non supportées

### ISSUE THREAD

**Issue by XavierJp** [etalab/annuaire-entreprises-site#461]
## Problème 

https://errors.data.gouv.fr/organizations/sentry/issues/464/events/?project=15&referrer=issue-stream&statsPeriod=14d

Certains filtres nature juridique ne passent pas
https://annuaire-entreprises.data.gouv.fr/rechercher?nature_juridique=5720

Le filtre 5720 n'est en réalité pas un filtre supporté par l'Insee.
idem avec 5498

## Solution

Mettre a jour la liste des natures juridiques et vérifier que ce sont les memes que celles de l'API

**Comment by XavierJp** [comment]
Liste des natures juridiques :
https://recherche-entreprises.api.gouv.fr/search?nature_juridique=5720

**Comment by HAEKADI** [comment]
Voici la liste utilisée côté API avec les libellés https://github.com/etalab/annuaire-entreprises-search-api/blob/main/aio/aio-proxy/aio_proxy/labels/natures-juridiques.json
