### ISSUE TITLE
Présentation de la liste des élus d'une collectivité

### ISSUE THREAD

**Issue by mquandalle** [etalab/annuaire-entreprises-site#549]
Quand je "parse" visuellement les informations affichées dans le tableau présentant la liste des élus d'une collectivité, j'ai l'impression que la colonne "rôle", qui n'est pas présente sur toutes les lignes, forme des groupes :

![image](https://github.com/etalab/annuaire-entreprises-site/assets/1730702/90d9db05-c2fd-47bb-a588-069d82e01d0b)

Comme si, dans la capture ci-dessus, il y avait 6 personnes dans la catégorie "3ème adjoint au maire". Or ce n'est évidemment pas comme cela qu'il faut comprendre ce tableau, il n'y a qu'un 3ème adjoint et les noms en dessous ont un rôle non renseigné.

Idées pour corriger ce problème :
- Mettre la colonne "rôle" en deuxième après la colonne "nom"
- ajouter un rôle "inconnu" / "non renseigné" (peut-être un peu lourd)
- avoir une séparation visuelle entre les lignes pour forcer l'interprétation ligne par ligne (fond zébré ou bordures)

**Comment by lmagreault** [comment]
Bonus : tri par rang (maire, 1er adjoint... pour une commune, président, vice-président... pour un EPCI)

**Comment by XavierJp** [comment]
Merci pour les suggestions ! 

Je trouve l'idée d'inverser les colonnes excellente, et elle pourrait s'appliquer également aux dirigeants d'entreprises et aux dirigeants d'administrations si on les ajoute dans #732 (@johangirod) 

Le tri par rang j'ai fait une première implémentation naive, les rang sont groupé mais pas ordonnés :
https://annuaire-entreprises.data.gouv.fr/elus/217500016

Quand à ajouter "Non renseigné" (en italique) c'est certes un peu lourd mais : 
- c'est déjà le standard du site
- ca a le mérite d'être beaucoup plus clair
