### ISSUE TITLE
[Espace Agents] Déporter les appels de l'espace agent dans le navigateur

### ISSUE THREAD

**Issue by XavierJp** [etalab/annuaire-entreprises-site#623]
Pair programming pour déporter la logique d'appel a API Entreprise vers le navigateur : 

- Activation de React pour la page entreprise pour les agents
- Appels asynchrones (depuis le client) pour ne pas entraver le chargement de la page
- Création d'une route d'API avec contrôle de session pour faire les appels

**Comment by Un3x** [comment]
Okay, 

J'ai un peu réfléchi au sujet et il faudrait tout de même qu'on se pose la question de la sécurité dans ce qu'on fait là. 

Si on fait des requêtes directement sur api entreprise depuis le front, n'importe qui qui regarde les échanges network pourrait reforger une requêtes avec d'autres données, à voir si c'est réserver sur la partie agent publique, mais même comme ca, le code js est accessible donc il pourrait reconstruire l'infos.

Si on fait un relais avec le backend, je pense que c'est mieux, mais même dans ces conditions on est probablement dans une situation où on ouvre une faille de sécu.

Notament au niveau de la donnée perso, s'il y a des échanges de data en clair avant obfuscation de la donnée selon le profil de l'utilisateur, c'est quand même beaucoup plus de travail qu'imaginé.

À discuter.
