### ISSUE TITLE
[CI] Refactor recipe-on-staging

### ISSUE THREAD

**Issue by XavierJp** [etalab/annuaire-entreprises-site#643]
Currently we use e2e tests on staging : https://github.com/etalab/annuaire-entreprises-site/actions/workflows/recipe-staging.yml

Since we protect staging with http basic auth and current strategy is not pretty bad as we test both API and staging site, we muste move to a new test strategy that only tests API responses.

Current responses mock are stored here :
https://github.com/etalab/annuaire-entreprises-site/tree/main/clients-mocks

**Comment by johangirod** [comment]
Proposed testing strategy : 
- We use mocked api call for E2E testing on staging
- We use non regression snapshot testing for all the api used

### Snapshot testing for APIs

- Runs every deploy + every day
- Retry if a service is unavailable
- Can be run locally with -u to update snapshot if the detected change is okay
- Runs from staging
- Tests every API possible
- Notify if an API changes (mattermost / email ?)
