### ISSUE TITLE
[Tech] Vérifier la compatibilité Edge & react

### ISSUE THREAD

**Issue by XavierJp** [etalab/annuaire-entreprises-site#699]
Lors d’un test utilisateur, @renardpal et moi-même avons pu remarquer que le style de la page dirigeant est cassé. L'animation en hauteur ne fonctionne pas correctement sur la partie résumé

**Comment by johangirod** [comment]
Je n'ai pas ce bug sur edge sur linux (Version 118.0.2088.57). Tu penses qu'il serait possible de le recontacter et lui demander un lien https://www.whatsmybrowser.org/ ?

**Comment by johangirod** [comment]
- 🟢  Firefox 78 : ok
- 🔴  Firefox 68 (< 0.1%) : KO 
- 🟢 Edge 108  : ok
- 🟢 Edge 97 ( < 0.1 %) : ok
- 🔴 Safari 12 : KO (< 0.1%) : KO


![Image](https://github.com/etalab/annuaire-entreprises-site/assets/1775934/601ed6b8-f95f-40d2-a4db-ca88e75ebf86)

**Comment by johangirod** [comment]
A priori corrigé. Ce type d'issue apparait dans sentry dorénavant. Par ailleurs, un travail a été fait pour tracker et afficher une erreur pour navigateurs non supportés.
