### ISSUE TITLE
Revoir l'Open Graph (OG title)

### ISSUE THREAD

**Issue by Jonathan2051** [etalab/annuaire-entreprises-site#716]
- **Problème** : le **titre** affiché lors d’un partage sur les réseaux sociaux est identique pour toutes les pages (Facebook et LinkedIn). Le titre de la page n'est pas personnalisé.

_NB : l'affichage des titres a été rendu impossible sur X / Twitter par Elon Musk_

- **Exemples** : 

**Linkedin**

![Image](https://github.com/etalab/annuaire-entreprises-site/assets/73166724/9aa2be99-6531-44fd-834e-f8dbbca0dd37)

**Facebook** 

![Image](https://github.com/etalab/annuaire-entreprises-site/assets/73166724/0d34e858-1ce8-4885-af55-10508245b4a3)

**X/Twitter**

![Image](https://github.com/etalab/annuaire-entreprises-site/assets/73166724/160097f7-5580-492b-998a-d3c95ceac5c5)

**Comment by XavierJp** [comment]
@johangirod seems like #727 did not fix the issue

**Comment by johangirod** [comment]
Are you sure ? It works on linkedin & facebook. Have you tried a new company ? There might be a cache for previously shared company.

**Comment by XavierJp** [comment]
@Jonathan2051 can you try it again but with a different company. Seems like old urls have been saved in a cache

**Comment by XavierJp** [comment]
According to me this is solved as Twitter / X no longer display titles
