### ISSUE TITLE
[TEST E2E] Allow to stub client-side request

### ISSUE THREAD

**Issue by johangirod** [etalab/annuaire-entreprises-site#761]
We are moving more and more fetch logic client side (e.g. #760 ). We need to allow for `stubClient` to work on this environment too, in order to be able to continue to use the testing infrastructure we designed for the project (E2E / api client).

Note : the apiClient test will continue to work, but not the E2E ones. 

File concerned : https://github.com/etalab/annuaire-entreprises-site/blob/main/clients/stub-client-with-snaphots.ts

**Comment by skelz0r** [comment]
I'm a little bit intrigued here: with your traffic why don't you move client-side call in your backend to control outside calls on your partners/providers (thanks to rate limiting/cache etc etc..) ? I'm confused because when you scale you move your client-side call to backend 😅

**Comment by johangirod** [comment]
We do the opposite here, for two reason : 
1. To avoid rate limiting from the externals API. All the OpenDataSoft APIs are open to use without authentication, but have a rate limiting that we reach on our server. 
2. To allow longer timeouts. If we had to wait on some APIs calls to complete before sending HTML to client, it would take more than 20s to load the page (especially with the INPI). We therefore calls those API from the browser, allowing longer timeout and possibility to navigate when it's loading.

**Comment by Un3x** [comment]
Why wouldn't you make ajax call to your server making calls to the API ? 

You coud both handle timeout and monitor properly calls and rate limit if needed.

I think there are already some example of this behavior for the api-entreprise calls.

**Comment by skelz0r** [comment]
For 1., if you are a proxy you can authenticate your calls (and have a lot more calls/perfs etc..), unauthenticated calls can be ban/limit anytime they want, you don't want this.
For 2., I don't get it, it's exactly the same but instead of calling directly the endpoint you are calling your endpoint which is a proxy: you can control timeout and stuff, which is a better approach

Moreover, you want to track errors, API calls, time etc etc.. data is key to better serve users.

**Comment by XavierJp** [comment]
Really happy to talk about this with you guys ! And curious about your insights. 

For a bit more context : 
- Historically every call were synchronously made from the server. This often raised two concerns : 
  - we only authorized calls to take up to ~3000ms to resolve. Yet :
     - it meant the application could feel sluggish at times   
     - it still wasnot enough for slow endpoints such as VIES, RNE, and event some ODS API
   - every producers saw us as one IP and if we reached our quotas, we got blocked and every users lost access to the data source
     - we could use IP rotation but it does not scale well
     - we could get whitelisted by every data producers but it takes time and does not scale well either
     - or we could put a huge pression on us being able to identify and prevent anyone to exhaust our quotas = fight against scrapping 

We did a bit of everything ^^ and we managed so far !

As Sirene and RNE are so important for SEO, we need them highly available, fast and server-rendered. So we are caching them. Eventually we would like to do the same for RNA as these three are the one we want indexed by the search engines. 

But we dont want to / cannot cache every data sources. Too much work, not enough womanpower :)

For the remaining datasources (https://annuaire-entreprises.data.gouv.fr/donnees/sources) we believe we have two choices : 
1. use our backend as a proxy and call it from a frontend component (i.e. what @skelz0r and @Un3x mentionned. See https://github.com/etalab/annuaire-entreprises-site/tree/main/pages/api/data-fetching). We also authenticated these routes #650 and they are rate limited. Yet if a quota is reached, our IP is blocked and everyone get blocked.
2. use the frontend to make the call without going through our server. If a quotas is reached, only the scrapper get blocked

Note that 2. only apply to very few API, mostly the ODS API and these are not called often : https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=145&period=day&date=yesterday#?period=day&date=2023-11-01&idSite=145&category=General_Actions&subcategory=General_Pages (page /annonces, /labels-certificats)

**Comment by Un3x** [comment]
IMO the best and correct way to go is server calls. But as said before it requires wo.manpower.

If you don't have it, it's not a technical decision anymore, but a strategic/temporary one.

**Comment by skelz0r** [comment]
> I dont know much about content security policy (CSP). Would it play a role here ?

For your case I don't think so.

tbh I was just curious because it's not a common decision to move API calls from back to front.

> But we dont want to / cannot cache every data sources. Too much work, not enough womanpower :)

And it's one thing in computer engineering that is [soooo complicated](https://martinfowler.com/bliki/TwoHardThings.html), so be careful when you will make some cache :D 

> IMO the best and correct way to go is server calls. But as said before it requires wo.manpower.

You can manage to make a generic proxy service, and enhance it step by step. The main key here is to monitor your external calls, which is, in my opinion, a critical data for your service. You can do it client side with a specific endpoint too, but it's more work for the client.

**Comment by johangirod** [comment]
> The main key here is to monitor your external calls, which is, in my opinion, a critical data for your service

For the monitoring part, every client call is logged to sentry, so we have good data : number, latency, error codes.
