### ISSUE TITLE
Tracker le nombre connexion depuis des navigateurs non supportés

### ISSUE THREAD

**Issue by johangirod** [etalab/annuaire-entreprises-site#776]
### Problème 

Comment determine-t-on le nombre de "browser outdated" ?

- compter le nombre de bandeaux outdated
- compter le nombre de page qui chargent react
- compter le nombre de page qui chargent vite

à comparer au total. 

Difficulté : comment connaitre le nombre exact de navigateurs ? Certains bloquent matomo, sont trop vieux ou ont désactivé javascript etc.

Méthodes que l'on peut mettre en oeuvre  : 
- event matomo
- sentry
- pixel de tracking (le seul qui va fonctionner sur les vieux vieux navigateurs)

NB : sur la frugalité, c'est peut etre pas la peine de logguer pour toutes les pages, et en meme temps c'est le plus simple

**Comment by johangirod** [comment]
Je ne comprends pas tellement l'intérêt de compter le nombre de page avec react / vite. Est-ce pour vérifier si des "outdated browser" ne sont pas pris en compte dans notre test pour afficher le warning ? Si c'est le cas, on le détectera vite avec Sentry.

Surtout grâce à la modification apportée dans #780 qui permet de ne pas envoyer les erreurs des navigateurs avec ce bandeau.

Alors qu'avec une métric matomo, on aura pas grand chose à se mettre sous la dent.

**Comment by XavierJp** [comment]
https://docs.sentry.io/platforms/javascript/troubleshooting/supported-browsers/
