### ISSUE TITLE
[BUG] Comment faire supprimer les données d'une ou plusieurs entreprises ?

### ISSUE THREAD

**Issue by UserCr4ig** [etalab/annuaire-entreprises-site#788]
J'ai cherché le fichier texte avec les protected siren, mais il n'existe plus. Y a-t-il donc un formulaire pour demander la non-diffusion ?

Bien a vous

**Comment by XavierJp** [comment]
Bonjour,

Suite au gain en popularité du projet nous avons changé de procédure. Désormais, vous pouvez effectuer la procédure [sur cette page](https://annuaire-entreprises.data.gouv.fr/faq/supprimer-donnees-personnelles-entreprise).

Je vais mettre a jour le README, merci pour votre issue.

Bonne journée,
