### ISSUE TITLE
Présence d'une balise H1 parasite sur l'Annuaire

### ISSUE THREAD

**Issue by Jonathan2051** [etalab/annuaire-entreprises-site#794]
La balise suivante apparaît dans le code html des pages de l'Annuaire : 

<H1> ⚠️ Votre navigateur est obsolète

Exemples : 

- https://annuaire-entreprises.data.gouv.fr/entreprise/carrefour-proximite-france-345130488
- https://annuaire-entreprises.data.gouv.fr/etablissement/34513048807871
- https://annuaire-entreprises.data.gouv.fr/entreprise/ville-de-paris-217500016
- https://annuaire-entreprises.data.gouv.fr/entreprise/congregation-des-filles-de-la-charite-paris-500728878
- https://annuaire-entreprises.data.gouv.fr/lp/entrepreneur-spectacles-vivants
- https://annuaire-entreprises.data.gouv.fr/definitions/bodacc

**Comment by XavierJp** [comment]
Cela vient du fait qu'avec les changements récents fait avec @johangirod on a mis ce warning systématiquement dans la page Html.
On avait pas pensé au robot, c'est un bug.
