### ISSUE TITLE
[FEATURE] Grouper conventions par IDCC

### ISSUE THREAD

**Issue by johangirod** [etalab/annuaire-entreprises-site#822]
- Dans la page `divers`
- Dans la section Conventions collectives

![Screenshot 2023-12-12 at 11-32-15 Conventions collectives - Société LA POSTE (DIRECTION GENERALE DE LA POSTE) à 75015 PARIS 15 - SIREN 356 000 000 Annuaire des Entreprises](https://github.com/etalab/annuaire-entreprises-site/assets/1775934/62ca27b4-709f-490b-b359-eb8ba460878a)

Il faudrait grouper les établissements avec la même convention. Cela permettrait de : 
- Gagner en lisibilité
- Faire un lien contextuel direct depuis le `Tag` `IDCC 1532` se trouvant sur la page `unité-légale`

**Comment by XavierJp** [comment]
Le regroupement a été fait dans #802
