### ISSUE TITLE
[BUG] Affichage date de naissance des élus

### ISSUE THREAD

**Issue by lmagreault** [etalab/annuaire-entreprises-site#847]
## Sujet du problème

Affichage date de naissance des élus

## Comment le reproduire ?

Page d'une collectivité territoriale

## Comportement attendu

Affichage de la date de naissance

## Comportement actuel

Mauvais affichage de la date

## Screenshots

![image](https://github.com/etalab/annuaire-entreprises-site/assets/677071/a0249696-f583-4191-a37c-97eeccea5ad1)

**Comment by XavierJp** [comment]
Merci pour votre vigilance, on va corriger le problème

**Comment by XavierJp** [comment]
@HAEKADI il semble que le bug se situe dans l'API : 

https://recherche-entreprises.api.gouv.fr/search?q=217500016
