### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by murcianos** [etalab/annuaire-entreprises-site#884]
## Votre demande de feature est-elle liée à un problème ?

Décrivez le problème.

## L’amélioration que vous avez en tête

Décrivez ce que vous aimeriez pouvoir faire. Exemple : « J’aimerais avoir la possibilité de… ». Si possible, ajoutez des captures ou des enregistrements de votre écran pour nous aider à visualiser la fonctionnalité.

## Les alternatives possibles

Si possible, décrivez d’autres façons de parvenir au résultat que vous espérez atteindre.

**Comment by XavierJp** [comment]
Je ferme cette issue qui n'a pas de description
