### ISSUE TITLE
[Annuaire Service public] Problème dans le parsing des affectations

### ISSUE THREAD

**Issue by XavierJp** [etalab/annuaire-entreprises-site#908]
https://errors.data.gouv.fr/organizations/sentry/issues/133955/events/?project=15&referrer=issue-stream

Premier fix naif : 
https://github.com/etalab/annuaire-entreprises-site/commit/6bc5df7182114a8f0007537ebf15ee0eaade0180

Mais des problèmes d'affichage persistent :
https://annuaire-entreprises.data.gouv.fr/dirigeants/752195438#responsables-service-public

**Comment by johangirod** [comment]
Bien vu ! Je m'y met dès lundi
