### ISSUE TITLE
[BUG] Investiguer les doublons dans les demande de non diffusible sur Grist

### ISSUE THREAD

**Issue by johangirod** [etalab/annuaire-entreprises-site#926]
Nous avons des doublons pour les demandes de suppressions de données du dirigeant dans Grist, quand bien même nous vérifions que la demande n'est pas déjà créée avant d'envoyer la requête POST à l'API Grist. Il y a en a 6 sur 106, ce qui est loin d'être négligeable.

Une piste d'explication serait la resoumission du formulaire depuis le client, via un double clique sur le bouton, ou un rechargement, lors de connexions lentes par exemple.

Mais je n'ai rien pour valider cela. 

A investiguer, donc.

**Comment by MKCG** [comment]
@johangirod , c'est bien ce qui se passe : certaines requêtes sont soumises deux fois à quelques dizaines de millisecondes d'intervalle.
C'est visible dans Kibana au sein de cette recherche enregistrée : https://kibana.recherche-entreprises.infra.api.gouv.fr/goto/c19e5090-d5bc-11ee-9c04-597428d9393e

Par exemple à 17h42m29s il y en a deux :
- https://kibana.recherche-entreprises.infra.api.gouv.fr/app/discover#/doc/filebeat-*/filebeat-000009?id=G7Ny640BL4395t38TiiI
- https://kibana.recherche-entreprises.infra.api.gouv.fr/app/discover#/doc/filebeat-*/filebeat-000009?id=FrNy640BL4395t38TiiI

A ce moment là il y a un seul log nginx qui correspond : https://kibana.recherche-entreprises.infra.api.gouv.fr/app/discover#/doc/filebeat-*/filebeat-000009?id=HrNy640BL4395t38QyD1

Est-ce qu'il y en a deux dans les logs car il y a d'abord une requête OPTIONS puis une requête POST ? Ou alors ce sont deux POST et il y a un problème de config quelque part ?


Ce serait également pas mal de rajouter la méthode HTTP utilisée dans les logs des requêtes : https://github.com/etalab/annuaire-entreprises-site/blob/main/utils/network/backend/log-interceptor.ts#L27

Une fois réalisé, il faudra modifier la pipeline filebeat utilisée pour ingérer ces logs afin de parser la méthode et la faire également remonter dans Kibana : https://github.com/etalab/annuaire-entreprises-infrastructure/blob/main/roles/docker-filebeat/files/pipelines/docker-std-annuaire-entreprises-site.json#L89

**Comment by johangirod** [comment]
Merci beaucoup pour tous ces éléments :purple_heart:  ! Je vais modifier les logs pour ajouter la méthode, et en profiter pour corriger #925

**Comment by MKCG** [comment]
@johangirod merci pour l'ajout des méthodes

De ce l'on voit il y a un HTTP GET juste avant un HTTP POST. C'est normal ?

![image](https://github.com/etalab/annuaire-entreprises-site/assets/8983434/c5d3ab5c-2d07-4b7e-bd16-2df81239a7be)


Je viens également de mettre à jour la pipeline filebeat pour parser la méthode HTTP et l'indiquer dans le tableau : 
![image](https://github.com/etalab/annuaire-entreprises-site/assets/8983434/be696a0b-53e2-4f4e-bc22-0bb1fdc8ab43)

https://github.com/etalab/annuaire-entreprises-infrastructure/pull/86

**Comment by johangirod** [comment]
Top pour le parsing ! C'est normal pour l'enchainement GET/POST, on vérifie d'abord si la personne n'a pas effectué déjà effectué une demande, avant de la créer.

**Comment by MKCG** [comment]
> Top pour le parsing ! C'est normal pour l'enchainement GET/POST, on vérifie d'abord si la personne n'a pas effectué déjà effectué une demande, avant de la créer.

Très clair, bon je ne trouve pas d'où proviennent les doublons avec les seuls logs Kibana. Il faudrait que l'on nous indique l'heure exacte à laquelle un nouveau doublon est apparu pour que l'on puisse creuser un peu plus.
