### ISSUE TITLE
Monitoring : Log des accès effectué par les agents

### ISSUE THREAD

**Issue by XavierJp** [etalab/annuaire-entreprises-site#976]
En tant que réutilisateur d'API Entreprise, l'Annuaire doit connaitre toutes les tentatives d'accès aux données restreintes. Et les conserver dans le cas ou un compte utilisateur serait corrompu.

Doivent être logés et consultables, pour chaque appel : 
- siret des orgas de l’usager (ex DINUM)
- email de l'usager ou slug agent connect (NB : email agent = donnée publique)
- route consultée sur API Entreprise
- cas d'usage juridique
- timestamp

Archivage : 3 mois

**Comment by MKCG** [comment]
On va les stocker dans des index spécifiques sur Elasticsearch : ça permet une séparation des flux de logs (sécurité) et permettra de réaliser des snapshots vers du S3 pour répondre à un besoin de stockage résilient

**Comment by MKCG** [comment]
Pull request côté infrastructure : https://github.com/etalab/annuaire-entreprises-infrastructure/pull/123
